---
- name: Install htop
  ansible.builtin.package:
    name: htop
    state: present
- name: Install python3
  ansible.builtin.package:
    name: python3
    state: present
- name: Install docker python package
  ansible.builtin.pip:
    name: docker
- name: Install docker python package
  ansible.builtin.pip:
    name: docker-compose