---
- name: Creates /home/nicholas/github/homelab/ directory
  file:
    path: /home/nicholas/github/homelab/
    state: directory
    mode: '0755'
- name: Copy dockercompose dir
  ansible.builtin.copy:
      src: /ansibleV2/homelab/dockercompose # this is where this repo lives on my jumpbox
      dest: /home/nicholas/github/homelab/
      follow: yes
      force: true
