- hosts: all
  tasks:
  - name: Install htop
    ansible.builtin.package:
      name: htop
      state: present
  - name: Install docker python package
    ansible.builtin.pip:
      name: docker
  - name: Install docker python package
    ansible.builtin.pip:
      name: docker-compose
  - name: deploy Docker Compose stack
    community.docker.docker_compose:
      project_src: /home/nicholas/github/homelab/homelab/dockercompose/portainer
      files:
      - compose.yaml
