---
- name: Install elk, jenkins, pihole, portainer, prometheus-grafana
  hosts: all
  become: true
  become_method: sudo

  roles:
    - packages
    - directory-setup
    - docker-compose
    - blackbox-exporter-setup
