apiVersion: 1

datasources:
- name: Prometheus
  type: prometheus
  url: http://prometheus:9090 
  isDefault: true
  access: proxy
  editable: true

- name: InfluxDB_v2_Flux
  type: influxdb
  access: proxy
  url: https://us-west-2-2.aws.cloud2.influxdata.com/
  jsonData:
    version: Flux
    organization: nick.turner82@gmail.com
    defaultBucket: ESP32Weather
    tlsSkipVerify: true
  secureJsonData:
    token: SbaFvDDHbTtCw5gpEUwj9VbCDS144RhoJK3hD9VIwXvljL7SP6dskLkOHovErUKuog0Pwd8-dqC1maCHzw-Q_A==
